INFO     BaseObject:base_objeckt.py:31 ('css selector', '.input-container #username') is visible
INFO     BaseObject:base_objeckt.py:31 ('xpath', "//*[@id='password']") is visible
INFO     BaseObject:base_objeckt.py:31 ('class name', 'logout-button') is visible
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9f4abc940>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/7debded9d9f6d6959789095e57a9c171/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9f4abfc70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/7debded9d9f6d6959789095e57a9c171/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9f4abfac0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/7debded9d9f6d6959789095e57a9c171/screenshot